### ISSUE TITLE
Porting plan

### ISSUE THREAD

**Issue by TMODER** [johnkeeping/usbmon2pcap#1]
Is there a plan that can be ported to Windows?

**Comment by johnkeeping** [comment]
`usbmon` is a Linux interface, I don't see how this utility could be useful on Windows.  Equally, the utility itself does not use any OS-specific interface so it should easily run on multiple operating systems and I'll consider PRs with portability fixes.

**Comment by TMODER** [comment]
Sorry, perhaps my description was inaccurate. What I meant was to have a tool on Windows that can directly convert usbmon.txt from Linux to pcap. Thank you for your answer anyway, I appreciate it!

**Comment by johnkeeping** [comment]
I don't think there's anything specific to the code that prevents it running on Windows, but I don't use Windows and have no way to try compiling it to check that.
